crates/air-interpreter-wasm/Cargo.lock

I guess it is an auto-replace artifact

Fix typo in Cargo.lock

---

avm/client/README.md
avm/client/build_wasm.ps1
avm/client/package.json

As I've discussed with @alari we should use air-interpreter only as a low-level concept and expose the whole package as `avm`
This PR renames the package from `air-interpreter` to `avm`

Rename air interpreter to avm

---

Cargo.lock
air-interpreter/Cargo.toml
air/Cargo.toml
avm/server/Cargo.toml
crates/air-parser/Cargo.toml
crates/interpreter-data/Cargo.toml
crates/interpreter-interface/Cargo.toml
crates/polyplets/Cargo.toml
crates/test-utils/Cargo.toml

`serde` version was strictly locked at `1.0.118` due to a breaking change in `1.0.119`. Now marine compiles with `serde 1.0.130` and it is possible to remove the strict requirement. This will avoid conflicts with crates that require `serde` newer than `1.0.118`. Same for `serde_json`.

Remove serde version lock on 1.0.118 and serde_json lock on 1.0.61

---

Cargo.toml
air/Cargo.toml

In #144 the second descrption for the `air` crate was accidentally added.

Delete double description field from Cargo.toml

---

Cargo.lock
air/Cargo.toml
avm/server/Cargo.toml

Bump AVM server crate in order to export server with updated polyplets

Bump AVM server version

---

air/src/execution_step/errors.rs
air/src/preparation_step/errors.rs
air/src/runner/outcome.rs
air/tests/test_module/integration/air_basic.rs

The interpreter returns 0 if supplied air is invalid due to the automatic error to int mapping by `strum`. This PR changes this scheme and force the interpreter to return not 0 in case of any error.

Change preparation error mapping

---

air/src/execution_step/air/call.rs
air/src/execution_step/air/fold_scalar.rs
air/src/execution_step/air/fold_stream.rs
air/src/execution_step/air/mod.rs
air/src/execution_step/air/par.rs
air/tests/test_module/integration/issue_180.rs
air/tests/test_module/integration/join_behaviour.rs
air/tests/test_module/integration/mod.rs

Before this PR:
- `call` sets `subtree_complete` to false in join behaviour
- `match`/`mismatch`/`fold` don't touch `subtree_complete` in join behaviour
- `par`'s subtree could be completed (`subtree_complete` = true) even if it's finished with a error (#180 was caused with this behaviour)
After this PR:
- `call`/`match`/`mismatch`/`fold` set `subtree_complete` to false in join behaviour
- `par` sets subtree complete to false if there's an error
Resolves #180.

Refactor join behaviour and par subtree completeness

---

Cargo.lock
avm/server/Cargo.toml
avm/server/src/avm.rs
avm/server/src/runner.rs
crates/air-lib/air-parser/src/parser/air.rs
crates/air-lib/lambda/parser/src/parser/va_lambda.rs

Adds a new API for getting memory size of a loaded interpreter:
```rust
pub fn memory_size(&self) -> usize { ... }
```

Add API for returning interpreter memory size

---

.circleci/config.yml
.github/workflows/publish_crates.yml
.github/workflows/publish_interpreter.yml
.github/workflows/publish_interpreter_dev.yml

`cargo-workspaces` fails to install on `nightly-2021-07-13`, as a result a part of crates can't be published in CI.

use Rust 2022-02-24 in CI

---

Cargo.lock
air/tests/test_module/features/tetraplets/security_tetraplets/auth_module/Cargo.lock
air/tests/test_module/features/tetraplets/security_tetraplets/log_storage/Cargo.lock
avm/server/src/runner.rs
crates/air-lib/test-utils/Cargo.toml
crates/air-lib/test-utils/src/test_runner.rs

Use pooled `avm::server::AVMRunner` instances of
air_iterpreter_server.wasm to reduce tests' running time.  It avoids
repeated WASM loading and compilation.
On my hardware, `cargo test --release` execution time (precompiled)
decreases from almost 6 minutes to 1.5 minutes.

Use pooled AVMRunner for tests

---

Cargo.lock
air/tests/test_module/instructions/fail.rs
crates/air-lib/air-parser/Cargo.toml
crates/air-lib/air-parser/src/ast/instruction_arguments/traits.rs
crates/air-lib/air-parser/src/ast/instructions/traits.rs
crates/air-lib/air-parser/src/ast/tests/instruction_arguments.rs
crates/air-lib/air-parser/src/ast/tests/instructions.rs
crates/air-lib/air-parser/src/ast/tests/mod.rs

There was a small typo in the `fn display_last_error`.
Closes #263

Fix Display of `Value::LastError` with a lambda

---

CHANGELOG.md
air/src/execution_step/air/call/call_result_setter.rs
air/src/execution_step/air/call/prev_result_handler.rs
air/src/execution_step/air/call/resolved_call.rs
air/src/execution_step/air/fail.rs
air/src/execution_step/air/fold_stream.rs
air/src/execution_step/air/mod.rs
air/src/execution_step/air/par.rs
air/src/execution_step/air/par/completeness_updater.rs
air/src/execution_step/air/seq.rs
air/src/execution_step/air/xor.rs
air/src/execution_step/execution_context/context.rs
air/src/execution_step/execution_context/scalar_variables.rs
air/tests/test_module/features/errors/last_error.rs
air/tests/test_module/issues/issue_178.rs
air/tests/test_module/issues/issue_180.rs
crates/air-lib/interpreter-data/src/executed_state/impls.rs
crates/air-lib/log-targets/src/lib.rs
crates/air-lib/trace-handler/README.md
crates/air-lib/trace-handler/src/handler.rs
crates/air-lib/trace-handler/src/lib.rs
crates/air-lib/trace-handler/src/merger/fold_merger/fold_lore_resolver.rs
crates/air-lib/trace-handler/src/state_automata/errors.rs
crates/air-lib/trace-handler/src/state_automata/fold_fsm/state_handler.rs
crates/air-lib/trace-handler/src/state_automata/mod.rs
crates/air-lib/trace-handler/src/state_automata/par_fsm.rs
crates/air-lib/trace-handler/src/state_automata/par_fsm/par_builder.rs
crates/air-lib/trace-handler/src/state_automata/par_fsm/state_handler.rs
crates/air-lib/trace-handler/src/state_automata/par_fsm/state_handler/new_states_calculation.rs

Intially, a fold instruction was designed based on idea that its iterable can't expand,
so AIR was considered as a subtree. But after introducing recursive streams in #225, it's
no more a subtree, but a subgraph.

Rename subtree to subgraph

---

air/tests/test_module/issues/issue_222.rs
air/tests/test_module/issues/mod.rs
crates/air-lib/trace-handler/src/state_automata/fold_fsm/lore_applier.rs

Set an empty subtrace on absent fold lore

---

.circleci/config.yml
avm/server/src/interface/call_service_result.rs
avm/server/src/interface/raw_outcome.rs
crates/air-lib/test-utils/Cargo.toml
crates/air-lib/test-utils/src/lib.rs
crates/air-lib/test-utils/src/native_test_runner.rs
crates/air-lib/test-utils/src/test_runner.rs
crates/air-lib/test-utils/src/wasm_test_runner.rs

As sanitizers are not available for WASM yet, AquaVM is run as native code with `--feature test_with_native_code` for these tests.
Closes #247.

Run tests with sanitizers

---

Cargo.lock
avm/server/Cargo.toml
avm/server/src/avm.rs
avm/server/src/errors.rs
avm/server/src/interface/outcome.rs
avm/server/src/interface/particle_parameters.rs
avm/server/src/lib.rs
crates/data-store/Cargo.toml
crates/data-store/src/lib.rs

This PR adds two new methods in `DataStore` to determine anomaly and collect necessary data. Additionally
- a generic parameter of `DataStore` turned to be associative
- `AVMOutcome` contains additionally `memory_delta` and `execution_time`

Add API to save anomaly data

---

Cargo.lock
air-interpreter/src/logger.rs

`jsonpath` has been used in early versions of AquaVM as lambda implementation, then it was replaced by our own simple lambda implementation, because of lack of standard and canonical realization. This filter option was forgotten to be deleted.

Remove `jsonpath` filter option

---

Cargo.lock
avm/interface/Cargo.toml
avm/server/Cargo.toml
avm/server/src/runner.rs

Needed for marine e2e to be able to build avm-server using marine-runtime from master.

Bump `marine-runtime` to `0.20.0`

---

air/src/lib.rs
avm/interface/src/lib.rs
crates/air-lib/air-parser/src/ast/values/impls.rs
crates/air-lib/air-parser/src/lib.rs
crates/air-lib/air-parser/src/parser/lexer/tests.rs
crates/air-lib/air-parser/src/parser/tests/ap.rs
crates/air-lib/air-parser/src/parser/tests/call.rs
crates/air-lib/air-parser/src/parser/tests/fail.rs
crates/air-lib/air-parser/src/parser/tests/match_.rs
crates/air-lib/execution-info-collector/src/lib.rs
crates/air-lib/interpreter-data/src/lib.rs
crates/air-lib/interpreter-interface/src/lib.rs
crates/air-lib/lambda/ast/src/lib.rs
crates/air-lib/lambda/parser/src/lib.rs
crates/air-lib/lambda/parser/src/parser/lambda_parser.rs
crates/air-lib/polyplets/src/lib.rs
crates/air-lib/test-utils/src/lib.rs
crates/air-lib/trace-handler/src/lib.rs
crates/data-store/src/lib.rs

Most of unsafe code is not really necessary.

Get rid of unsafe code in the interpreter

---

Cargo.lock
air-interpreter/Cargo.toml
air/Cargo.toml

Bump `wasm-bindgen` crate version in order to merge #309. Also unused `wasm-bingen` from the main `air` crate was removed.

bump wasm-bindgen

---

.github/workflows/air_tag_release.yml
.github/workflows/aquavm.yml
.github/workflows/publish_crates.yml
.github/workflows/publish_interpreter.yml
.github/workflows/publish_interpreter_dev.yml
.github/workflows/rustdoc.yml
Cargo.lock
crates/data-store/src/lib.rs
rust-toolchain.toml

- Added `rust-toolchain.toml` file so rust toolchain is the same when running rust locally and with CI.
No need to specify channel or components in github workflow file now.
- Changed `Setup rust toolchain` step to use different action. Old one is not maintained anymore. Beware that it sets these env variables by default:
```
CARGO_INCREMENTAL=0
CARGO_PROFILE_DEV_DEBUG=0
CARGO_TERM_COLOR=always
RUST_BACKTRACE=short
RUSTFLAGS=-D warnings
```

Use rust-toolchain to setup rust

---

Cargo.lock
avm/server/Cargo.toml

The crate version wasn't updated in #299, so this PR will fix it and new version will be finally released.

Bump avm-server version to 0.26.0

---

air/src/execution_step/air/ap/apply_to_arguments.rs
air/src/execution_step/air/canon.rs
air/src/execution_step/boxed_value/canon_stream.rs
air/tests/test_module/issues/issue_331.rs
air/tests/test_module/issues/mod.rs
crates/air-lib/test-utils/src/test_runner.rs

This PR changes scheme how positions in `ap` are assigned for values constructed from canonicalized streams.
Resolves #331.

Fix canon positions

---

air/tests/test_module/issues/issue_348.rs
air/tests/test_module/issues/mod.rs
crates/air-lib/trace-handler/src/merger/canon_merger.rs

fix(trace-handler): treat `ap` states with different generations as compatible for `canon`

---

air/src/execution_step/air/ap.rs
air/src/execution_step/air/ap/utils.rs
air/src/execution_step/air/call/call_result_setter.rs
air/src/execution_step/air/call/prev_result_handler.rs
air/src/execution_step/air/call/resolved_call.rs
air/src/execution_step/air/canon.rs
air/src/execution_step/errors/uncatchable_errors.rs
air/tests/test_module/features/streams/streams_early_exit.rs
air/tests/test_module/issues/issue_295.rs
crates/air-lib/trace-handler/src/handler.rs
crates/air-lib/trace-handler/src/lib.rs
crates/air-lib/trace-handler/src/merger/call_merger.rs
crates/air-lib/trace-handler/src/merger/call_merger/utils.rs
crates/air-lib/trace-handler/src/merger/errors.rs
crates/air-lib/trace-handler/src/merger/mod.rs
crates/air-lib/trace-handler/src/state_automata/errors.rs
crates/air-lib/trace-handler/src/state_automata/fold_fsm/state_handler.rs
crates/air-lib/trace-handler/src/state_automata/mod.rs
next-hardfork-changes.md

This PR refactors call merger of `TraceHandler`. Previously it requires `CallOutputValue` to determine a type of call output value (stream or scalar). And internally it checked correspondence betweendata result and call output type and return a error if they are not equal. Although execution engine component also had a `match` over these values and does nothing if they are not matched since `TraceHandler` did this job. This PR eliminate such behaviour and improve isolation of AquaVM modules.

refactor(aquavm): getting rid of `CallOutputValue` in call merger

---

crates/testing-framework/src/transform/parser.rs

While exclamation mark is legacy feature in the lambda parser, people seem to use it anyway, getting errors not always easy to understand.

feat(testing-framework): allow exclamation mark

---

Cargo.lock
crates/testing-framework/Cargo.toml
crates/testing-framework/src/execution/mod.rs

Try to parse the annotated AIR script with the standard parser to catch to catch errors early with better error messages.
We do it in the `TestExecutor` only to make testing framwork parser tests simplier.  For user experience, it doesn't matter.

feat(testing-framework): prevalidate AIR script

---

air/src/preparation_step/errors.rs

Data is printed last as it is very long and makes it difficult to find the original error message.

feat(air): More convenient error messages

---

.github/renovate.json

- do not group versions update in one PR (unless grouped by default i.e. `jest`)
- max 10 open PR
- max 1 open major bump PR
- dev dependencies have lowest priority
- runs only on weekends

ci: Renovate tuning

---

crates/testing-framework/src/asserts/behavior.rs
crates/testing-framework/src/asserts/mod.rs
crates/testing-framework/src/asserts/parser.rs
crates/testing-framework/src/execution/mod.rs
crates/testing-framework/src/services/mod.rs
crates/testing-framework/src/services/results.rs

Add `behavior=tetraplet` for testing framework annotation to return call's tetraplet.

feat(testing-framework): tetraplet behavior

---

crates/air-lib/interpreter-cid/Cargo.toml

The serde crate was missing "derive" feature.

fix(interpreter-cid): Fix interpreter-cid compilation

---

crates/air-lib/interpreter-cid/Cargo.toml

It was too long, and the crate was rejected by the crates.io.

fix(interpreter-cid): fix Cargo.toml keyword list

---

CHANGELOG.md
Cargo.lock
air-interpreter/Cargo.toml
air/Cargo.toml
avm/interface/CHANGELOG.md
avm/interface/Cargo.toml
avm/interface/src/raw_outcome.rs
avm/server/CHANGELOG.md
avm/server/Cargo.toml
crates/air-lib/interpreter-interface/CHANGELOG.md
crates/air-lib/interpreter-interface/Cargo.toml
crates/air-lib/interpreter-interface/src/interpreter_outcome.rs
rust-toolchain.toml

The `InterpreterOutcome::cid` field is not really needed, but makes integration more difficult.

fix(interpreter-interface): Remove the `cid` field

---

rust-toolchain.toml

Newer toolchain enables bulk-memory target feature that is not compatible with our wasmer version.

chore: Fix rust toolchain version

---

rust-toolchain.toml

I experienced some problems with the current rust toolchain version:
```
Compiling once_cell v1.16.0
error[E0463]: can't find crate for `std`
error[E0463]: can't find crate for `core`
```

chore(ci): change pinned rust toolchain version

---

air/Cargo.toml

chore(deps): Bump fluence-app-service to 0.23.0

---

.github/renovate.json
.github/workflows/ci.yml
.github/workflows/e2e.yml
.github/workflows/release.yml
.github/workflows/snapshot.yml

Please add `e2e / status` to required checks
- notify on release failure to slack
- run renovate any time for fluencelabs dependencies and use prefix fix(deps) for them
- add `e2e / status` check that should be set as required for PR before merge (please do it in settings before merge)

chore(ci): Notify on release failures and other small CI changes [fixes FLU-222, FLU-194, FLU-41 and FLU-196]

---

air/src/execution_step/errors/catchable_errors.rs
air/src/execution_step/instructions/call.rs
air/src/execution_step/instructions/xor.rs

Users complain that `warn` level produces lot of unnecessary logs.
+ join behavior logging is demoted to `trace`;
+ xor logging is demoted to `trace`;
+ service error logging is demoted to `debug`.

fix(air): demote some AquaVM logging statements

---

air/tests/test_module/negative_tests/mod.rs
air/tests/test_module/negative_tests/uncatchable_trace_unrelated.rs

chore(execution-engine): a set of trace-unrelated negative tests for UncatableError [fixes VM-263]

chore(execution-engine): a set of trace-unrelated negative tests for UncatableError [fixes VM-263]

---

.github/release-please/config.json
Cargo.lock
air/tracing_benches.sh
tools/cli/air/Cargo.toml
tools/cli/air/README.md
tools/cli/air/src/trace/run.rs
tools/cli/air/src/trace/run/data/plain.rs
tools/cli/performance_metering/performance_metering/bench.py

1. `air run --plain --data` is renamed to `… --current-data` and made optional.
2. if AIR script is read from stdin, a message is printed.  Otherwise use may wait indefinitely if he/she doesn't know that script is read from stdin by default.
3. fix release-please config.

feat(aquavm-air-cli)!: Usability enhancements

---

Cargo.lock
Cargo.toml
air/Cargo.toml
air/src/execution_step/execution_context/context.rs
air/src/execution_step/instructions/call/call_result_setter.rs
air/src/execution_step/instructions/call/prev_result_handler.rs
air/src/execution_step/instructions/canon.rs
air/src/farewell_step/outcome.rs
air/src/preparation_step/preparation.rs
air/src/runner.rs
air/tests/test_module/features/mod.rs
air/tests/test_module/features/signatures.rs
air/tests/test_module/negative_tests/uncatchable_trace_related.rs
crates/air-lib/interpreter-cid/src/lib.rs
crates/air-lib/interpreter-data/Cargo.toml
crates/air-lib/interpreter-data/src/executed_state/impls.rs
crates/air-lib/interpreter-data/src/interpreter_data.rs
crates/air-lib/interpreter-signatures/Cargo.toml
crates/air-lib/interpreter-signatures/src/lib.rs
crates/air-lib/test-utils/src/lib.rs

A peer signs call results and canon results it has produced.
New field `signatures`, a map from peer public key to signature, is added to the interpreter data.
Signatures checking is yet to be done.

feat(aquavm-air,air-interpreter-signature,air-interpreter-data)!: Peer signatures

---

crates/air-lib/interpreter-signatures/src/lib.rs
crates/air-lib/interpreter-signatures/src/sede.rs

Wrapper types do not hold strings anymore, but use `(de)serialize_with` serde attributes to parse keys and signatures during parse time.
`PublicKey` and `Signature` traits implement `Deref` trait that returns the inner value.

feat(air-interpreter-signatures): use (de)serialize_with

---

air/src/execution_step/errors/catchable_errors.rs
air/tests/test_module/instructions/match_.rs
air/tests/test_module/instructions/mismatch.rs
crates/testing-framework/src/execution/mod.rs

feat(execution-engine)!: add error-code invariant check for match/mismatch

feat(execution-engine)!: add error-code invariant check for match/mismatch

---

air/src/execution_step/boxed_value/stream.rs
air/src/execution_step/boxed_value/stream_map.rs
air/src/execution_step/instructions/canon.rs
air/src/execution_step/instructions/canon_stream_map_scalar.rs

This PR moves the creation of a stream with unique keys from `Stream` to `StreamMap` to improve code isolation. Before this PR `Stream` has known about `StreamMapKey` which wasn't compatible with the dependencies flow.
It is needed in order to support #621.

chore(execution-engine): move get_unique_map_keys_stream into StreamMap

---

air/src/execution_step/boxed_value/canon_stream.rs
air/src/execution_step/boxed_value/stream.rs
air/src/execution_step/boxed_value/stream_map.rs
air/src/execution_step/execution_context/cid_state.rs
air/src/execution_step/instructions/call/call_result_setter.rs
air/src/execution_step/instructions/call/prev_result_handler.rs
air/src/execution_step/instructions/canon.rs
air/src/execution_step/instructions/canon_stream_map_scalar.rs
air/src/execution_step/instructions/canon_utils/mod.rs
air/src/execution_step/instructions/mod.rs
air/tests/test_module/features/cid/canon.rs
air/tests/test_module/negative_tests/uncatchable_trace_unrelated.rs
crates/air-lib/interpreter-data/src/cid_store.rs
crates/air-lib/interpreter-data/src/executed_state/impls.rs
crates/air-lib/test-utils/src/executed_state.rs

- refactor canon instruction implementation
- `get_stream_or_default` creates a new `CanonStream` instead of returning a stream 
- `record_value` renamed to `track_value`
In order to support #621.

chore(execution-engine): refactor unseen canon stream creation

---

.github/workflows/tests.yml

In the PR #607 tests are not compatible with some feautre flags yet.
Disable `llvm-cov`'s `--all-feautres` until all the tests are fixed.
For now, run `llvm-cov` only with default features.

chore: run llvm-cov on default features only

---

crates/air-lib/air-parser/src/parser/lexer/call_variable_parser.rs
crates/air-lib/air-parser/src/parser/lexer/errors.rs
crates/air-lib/air-parser/src/parser/lexer/tests.rs

Maps proposal adds a new way to access canon streams and maps using # sign prefix, e.g. #$canon_stream, #%canon_map.  This patch adds support for # prefix accessing canon structures.

feat(air-parser): canon stream syntax

---

.github/workflows/e2e-label.yml

bot users (like default github-bot) don't trigger CI

chore: Add e2e label as fluencebot to trigger e2e

---

tools/cli/air/src/trace/run.rs

It will make easier to add new modes.

chore(aquavm-air-cli): dedicated type for execution mode

---

crates/air-lib/air-parser/src/parser/span.rs

It was vice versa.  The problem was found by clippy.

chore: `PartialOrd` uses `Ord`'s implementation

---

Cargo.lock
tools/cli/air/src/trace/run.rs
tools/cli/air/src/trace/run/near.rs
tools/wasm/air-near-contract/Cargo.lock

1. Correct default contract path.
2. More informative error messages.
3. Deserialize contract result correctly.

fix(aquavm-air-cli): NEAR mode fixes

---

air/src/execution_step/errors/uncatchable_errors.rs
air/src/execution_step/execution_context/stream_maps_variables.rs
air/src/execution_step/execution_context/streams_variables.rs
air/src/execution_step/instructions/ap.rs
air/src/execution_step/instructions/ap_map.rs
air/src/execution_step/instructions/call/call_result_setter.rs
air/src/execution_step/mod.rs
air/src/execution_step/value_types/mod.rs
air/src/execution_step/value_types/stream/mod.rs
air/src/execution_step/value_types/stream/recursive_stream.rs
air/src/execution_step/value_types/stream/stream_definition.rs
air/src/execution_step/value_types/stream/values_matrix.rs
air/src/execution_step/value_types/stream_map.rs
air/tests/test_module/features/streams/recursive_streams.rs
air/tests/test_module/negative_tests/uncatchable_trace_unrelated.rs

The Stream size limit controls how many values can be stored in a Stream to resolve self-feeding recursive stream case. The example below now stops after 1024 fold iterations.
```
(seq
(ap 42 $stream)
(fold $stream i
(seq
(ap i $stream)
(next i)
)
) 
)
```

feat(execution-engine)!: this introduces a hardcoded limit for a number of values in a stream [fixes VM-324]

---

air/src/execution_step/instructions/canon.rs
air/src/execution_step/instructions/canon_stream_map_scalar.rs
air/src/execution_step/instructions/canon_utils/mod.rs
air/src/execution_step/value_types/stream/stream_definition.rs
air/src/execution_step/value_types/stream_map.rs
air/tests/test_module/instructions/canon.rs
air/tests/test_module/negative_tests/uncatchable_trace_related.rs
crates/air-lib/interpreter-data/src/executed_state.rs
crates/air-lib/interpreter-data/src/executed_state/impls.rs
crates/air-lib/test-utils/src/executed_state.rs
crates/air-lib/test-utils/src/lib.rs
crates/air-lib/trace-handler/src/merger/canon_merger.rs

If `canon` is to be executed on another peer and the particle is to be
sent here, current peer inserts canon request-sent-by state to avoid
repeated requests, similar to `call` instruction.

feat(execution-engine,interpreter-data)!: insert state for canon join

---

air/src/execution_step/instructions/canon_utils/mod.rs
air/tests/test_module/instructions/canon.rs

Implement join behavior for `canon`'s first argument `peer_id`.  It simplifies generating code in Aqua compiler when `peer_id` is defined by a variable defined in a `par` branch.

feat(execution-engine): join behavior for canon

---

air/src/execution_step/execution_context/context.rs

This is a forgotten change for the maps patch.

fix(execution-engine): ExecutionCtx fmt now prints stream maps out

---

air/src/execution_step/execution_context/stream_maps_variables/stream_map_key.rs
air/src/execution_step/instructions/canon_map.rs
air/src/execution_step/value_types/stream_map.rs
air/tests/test_module/instructions/canon.rs

Previously `#%canon_map.$.[key]` returned FWW value from an underlying stream.

fix(execution-engine)!: canon map lens access now returns a correct number of kvpairs in a canon stream

---

.github/workflows/tests.yml
air-interpreter/Cargo.toml

Make `gen_signatures` and `check_signature` features defaults.

feat(air-interpreter)!: enable signature generation and verification features

---

air-interpreter/src/logger.rs
air-interpreter/src/marine.rs

A hacky way to prevent multiple initialization of a tracing subscruber.
This is a prerequisite to add benchmarking tests for nox.

fix(air-interpreter): enable multiple invoke_tracing calls for air-interpreter

---

air/src/lib.rs
air/src/preparation_step/preparation.rs
benches/PERFORMANCE.json
benches/PERFORMANCE.txt
crates/air-lib/air-parser/benches/parser.rs
crates/air-lib/air-parser/src/ast/instructions.rs
crates/air-lib/air-parser/src/ast/instructions/impls.rs
crates/air-lib/air-parser/src/parser/air.lalrpop
crates/air-lib/air-parser/src/parser/air.rs
crates/air-lib/air-parser/src/parser/air_parser.rs
crates/air-lib/air-parser/src/parser/tests/call.rs
crates/air-lib/air-parser/src/parser/tests/dsl.rs
crates/air-lib/air-parser/src/parser/tests/mod.rs
crates/beautifier/src/beautifier.rs
junk/gen-bench-data/gen_benchmark_data.sh
junk/gen-bench-data/src/main.rs

Instead of being boxed for each node, the `Instruction` type contains a boxed variable-size elements.  Thus `Instruction` is quite lean, and the allocator deals with variable-sized elements.
Total number of allocations is more or less same, but less space is wasted for unused memory: previously the Instruction's size was 112 bytes in WASM, now it is 16.
It reduces memory consumption on large AIR scripts (heap size decreased from 7.7MiB to 4.625MiB in parser-10000-100, and for the new parser-calls-10000-100 benchmark, it decreased from 5.115MiB to 4.375MiB).
This is a breaking change as the API changes (though the code that navigates the parsed tree generally should work as is).

feat(air-parser)!: optimize Instruction type layout

---

avm/client/package-lock.json
avm/client/package.json
avm/client/src/avmHelpers.ts
avm/client/src/formats.ts
avm/client/src/index.ts

For parsing and producing call requests and call results in AquaVM-compatible way with JSON and MessagePack.
Multicodec representation is also supported, both JSON and MessagePack can be used as input.

feat(avm-client): implement pluggable formats in JS

---

junk/gen-bench-data/gen_benchmark_data.sh
junk/gen-bench-data/src/main.rs
junk/gen-bench-data/src/mem_consumption_hybrid.air.tmpl

This adds a mixed workload test to monitor memory consumption.

chore(performance,tests):  hybrid workload memory intensive test

---

air/src/preparation_step/errors.rs
air/src/preparation_step/preparation.rs
air/tests/test_module/negative_tests/preparation_step.rs

Some preparation step errors increases data consumption printout data out. This patch removes data from preparation step errors to save some RAM bytes.

fix(performance): data printout removal some preparation step errors increases data consumption printout data out

---

crates/air-lib/interpreter-interface/src/interpreter_outcome.rs

This convenience method hides internal repr from nox

feat(avm-server): add a convenience method to hide implementation from nox

---

Cargo.lock
air/src/execution_step/instructions/call/resolved_call.rs
air/tests/test_module/features/tetraplets/security_tetraplets/auth_module/Cargo.lock
air/tests/test_module/features/tetraplets/security_tetraplets/log_storage/Cargo.lock
crates/air-lib/interpreter-sede/src/format.rs
crates/air-lib/interpreter-value/src/value/mod.rs
junk/gen-bench-data/Cargo.lock
rust-toolchain.toml

It requires updating minor version of curve25519-dalek crate in the Cargo.lock.  If you need to use older version of nightly rustc, use curve25519-dalek-4.1.1.  It affects Cargo.lock only.

chore: Rust channel update dedicated to ENIAC Day

---

.github/workflows/e2e.yml
avm/client/src/avmHelpers.ts

This fixes the 'invoke' call incorrect argument type issue for js-client.

fix(avm-client)!: this fixes the last argument type for WASM module 'invoke' function

---

air/src/execution_step/instructions/fold/utils.rs
air/tests/test_module/instructions/fold.rs

A O(n) fix for the canon map reverse iteration bug.

fix(execution-engine): quickfix for canon map iteration order

---

crates/air-lib/interpreter-value/src/value/index.rs
tools/cli/air/src/main.rs

fix(value): remove unused code
