fluencelabs/aquavm

.github/workflows/publish_interpreter.yml
.github/workflows/publish_interpreter_dev.yml

Switch to CommonJS modules instead of ESM

Switch to cjs

---

Cargo.lock
air/tests/test_module/instructions/call.rs
air/tests/test_module/integration/air_basic.rs
air/tests/test_module/integration/dashboard.rs
air/tests/test_module/integration/data_merge.rs
air/tests/test_module/integration/flattening.rs
air/tests/test_module/integration/join.rs
air/tests/test_module/integration/last_error.rs
air/tests/test_module/integration/streams.rs
avm/server/Cargo.toml
avm/server/src/avm.rs
avm/server/src/call_service.rs
avm/server/src/config.rs
avm/server/src/data_store.rs
avm/server/src/errors.rs
avm/server/src/lib.rs
crates/test-utils/src/lib.rs

Also added function to cleanup directories after a particle

Particle File Vault

---

air/src/execution_step/air/compare_matchable/comparator.rs
air/tests/test_module/instructions/match_.rs

fix behaviour with compare values after applying lambda

---

air/src/execution_step/air/call/prev_result_handler.rs
air/src/execution_step/air/call/resolved_call.rs
air/tests/test_module/instructions/fold.rs
air/tests/test_module/instructions/new.rs

Track previous call state after join behaviour

---

air/src/execution_step/air/compare_matchable/comparator.rs
air/tests/test_module/issues/issue_206.rs
air/tests/test_module/issues/mod.rs

Fix bug with empty arrays in match

---

Cargo.lock
air/src/execution_step/air/fold/utils.rs
air/src/execution_step/boxed_value/jvaluable/iterable_item.rs
air/src/execution_step/boxed_value/jvaluable/resolved_call_result.rs
air/src/execution_step/lambda_applier/applier.rs
air/src/execution_step/lambda_applier/errors.rs
air/src/execution_step/lambda_applier/mod.rs
air/src/execution_step/lambda_applier/utils.rs
air/src/execution_step/resolver/resolve.rs
air/tests/test_module/integration/lambda.rs
air/tests/test_module/issues/issue_211.rs
air/tests/test_module/issues/mod.rs

Previously, scalars in lambda for stream was unimplemented. This PR adds implementation for them.
Fixes #211.

Implement scalars in lambda for streams

---

Cargo.lock
air/src/execution_step/air/call/resolved_call.rs
air/src/execution_step/execution_context/streams_variables.rs
air/tests/test_module/instructions/fold.rs
air/tests/test_module/integration/lambda.rs
air/tests/test_module/integration/last_error.rs
air/tests/test_module/issues/issue_214.rs
air/tests/test_module/issues/mod.rs
avm/server/Cargo.toml

Check call arguments at the beggining

---

air/src/execution_step/air/ap.rs
air/src/execution_step/air/call/resolved_call.rs
air/tests/test_module/issues/issue_216.rs
air/tests/test_module/issues/mod.rs

Fix data handling in ap

---

air/src/execution_step/air/ap.rs
air/src/execution_step/air/ap/apply_to_arguments.rs
air/src/execution_step/air/call.rs
air/src/execution_step/air/call/call_result_setter.rs
air/src/execution_step/air/call/prev_result_handler.rs
air/src/execution_step/air/call/resolved_call.rs
air/src/execution_step/air/fail.rs
air/src/execution_step/air/fold/utils.rs
air/src/execution_step/boxed_value/iterable.rs
air/src/execution_step/boxed_value/iterable/json_path_result.rs
air/src/execution_step/boxed_value/iterable/vec_json_path_result.rs
air/src/execution_step/boxed_value/jvaluable.rs
air/src/execution_step/boxed_value/jvaluable/cell_vec_resolved_call_result.rs
air/src/execution_step/boxed_value/jvaluable/empty_stream.rs
air/src/execution_step/boxed_value/jvaluable/iterable_item.rs
air/src/execution_step/boxed_value/jvaluable/resolved_call_result.rs
air/src/execution_step/boxed_value/jvaluable/stream.rs
air/src/execution_step/boxed_value/scalar.rs
air/src/execution_step/execution_context/last_error/last_error_definition.rs
air/src/execution_step/execution_context/last_error/last_error_descriptor.rs
air/src/execution_step/mod.rs
air/src/execution_step/resolver/mod.rs
air/src/execution_step/resolver/resolve.rs
air/tests/test_module/integration/security_tetraplets.rs

Fix tetraplets json path

---

air/src/execution_step/air/fold_scalar.rs
air/tests/test_module/instructions/fold.rs
crates/air-lib/air-parser/src/ast/instruction_arguments.rs
crates/air-lib/air-parser/src/ast/instruction_arguments/traits.rs
crates/air-lib/air-parser/src/ast/instructions.rs
crates/air-lib/air-parser/src/ast/instructions/impls.rs
crates/air-lib/air-parser/src/parser/air.lalrpop
crates/air-lib/air-parser/src/parser/air.rs
crates/air-lib/air-parser/src/parser/tests/dsl.rs
crates/air-lib/air-parser/src/parser/tests/fold.rs
crates/air-lib/air-parser/src/parser/validator.rs

support empty array literal in fold

---

CHANGELOG.md
Cargo.lock
air-interpreter/Cargo.toml
air/Cargo.toml
air/src/execution_step/air/ap/apply_to_arguments.rs
air/src/execution_step/air/call/resolved_call.rs
air/src/execution_step/air/fold/utils.rs
air/src/execution_step/air/new.rs
air/src/execution_step/errors/catchable_errors.rs
air/src/execution_step/errors/uncatchable_errors.rs
air/src/execution_step/execution_context/scalar_variables.rs
air/src/execution_step/lambda_applier/applier.rs
air/src/execution_step/resolver/resolve.rs
air/tests/test_module/features/scopes/scalars_scope.rs
air/tests/test_module/instructions/call.rs
air/tests/test_module/instructions/new.rs
air/tests/test_module/instructions/xor.rs
crates/air-lib/air-parser/src/parser/tests/new.rs

Introduce new for non iterable scalars

---

Cargo.lock
avm/server/Cargo.toml
avm/server/src/avm.rs
crates/data-store/Cargo.toml
crates/data-store/src/lib.rs

Add it to the particle_data, where it belongs logically.

Add AIR script to the AquaVM's anomaly data

---

air/benches/data/big.air
air/benches/data_big_benchmark.rs
air/tracing_benches.sh

It accepts two arguments: `big`/`long` test type and `merge`/`nomerge`
test subtype.  Any of arguments can be replaced with `--all` value.

Introduce `tracing_benches.sh` script

---

air/tests/test_module/issues/issue_295.rs
air/tests/test_module/issues/mod.rs
crates/air-lib/air-parser/src/parser/air.rs
crates/air-lib/lambda/parser/src/parser/va_lambda.rs
crates/air-lib/trace-handler/src/merger/ap_merger.rs

Fix bug with ap merger

---

air/src/execution_step/execution_context/context.rs
air/src/execution_step/execution_context/streams_variables.rs
air/src/preparation_step/preparation.rs
air/tests/test_module/issues/issue_300.rs
air/tests/test_module/issues/mod.rs

Populate restricted streams generations from data

---

air/src/execution_step/air/fold_scalar.rs
air/tests/test_module/issues/issue_304.rs
air/tests/test_module/issues/mod.rs

The AquaVM returned an error instead of joinging.
Resolves #304

Bug: join behavior on CanonStream

---

Cargo.lock
avm/interface/CHANGELOG.md
avm/interface/Cargo.toml
avm/server/CHANGELOG.md
avm/server/Cargo.toml
crates/air-lib/interpreter-interface/CHANGELOG.md
crates/air-lib/interpreter-interface/Cargo.toml
crates/air-lib/polyplets/CHANGELOG.md
crates/air-lib/polyplets/Cargo.toml
crates/data-store/CHANGELOG.md
crates/data-store/Cargo.toml

* `air-interpreter-interface` -> 0.11.1
* `polyplets` -> 0.3.2
* `avm-interface` -> 0.26.1
* `avm-data-store` -> 0.4.1
* `avm-server` -> 0.26.1
---
This PR was generated with [release-plz](https://github.com/MarcoIeni/release-plz/).

chore: release

---

Cargo.lock
air/src/preparation_step/errors.rs
air/src/preparation_step/interpreter_versions.rs
air/src/preparation_step/mod.rs
air/src/preparation_step/preparation.rs
air/tests/test_module/features/data_merging/data_merge.rs
air/tests/test_module/features/misc/version_check.rs
air/tests/test_module/negative_tests/mod.rs
air/tests/test_module/negative_tests/preparation_step.rs
crates/air-lib/interpreter-data/CHANGELOG.md
crates/air-lib/interpreter-data/Cargo.toml
crates/air-lib/interpreter-data/src/interpreter_data.rs
crates/air-lib/test-utils/src/lib.rs

Aims to make an error message more clear when data of incompatible versions is used.

feat(trace-handler): improve data deserialization version check

---

next-hardfork-changes.md

Add two more data format and structure changes

chore(docs): add more upcoming data changes

---

.github/release-please/manifest.json
Cargo.lock
air-interpreter/Cargo.toml
air/Cargo.toml
crates/air-lib/air-parser/Cargo.toml
crates/air-lib/execution-info-collector/Cargo.toml
crates/air-lib/interpreter-data/CHANGELOG.md
crates/air-lib/interpreter-data/Cargo.toml
crates/air-lib/lambda/parser/Cargo.toml
crates/air-lib/test-utils/CHANGELOG.md
crates/air-lib/test-utils/Cargo.toml
crates/air-lib/trace-handler/Cargo.toml
crates/testing-framework/Cargo.toml
tools/cli/air-beautify/Cargo.toml
tools/cli/air-trace/CHANGELOG.md
tools/cli/air-trace/Cargo.toml

- revert previous release
- set dependencies version everywhere

chore(ci): Revert previous release, prepare for new release [fixed FLU-271]

---

Cargo.lock
air-interpreter/Cargo.toml

chore: Force air-interpreter version

---

.github/workflows/ci.yml
README.md

covecov check result is not added for some reason. But maybe if merge it will start to work.
https://coveralls.io/github/fluencelabs/aquavm

chore(ci): Add codecov

---

air/tests/test_module/negative_tests/mod.rs
air/tests/test_module/negative_tests/uncatchable_trace_related.rs
air/tests/test_module/negative_tests/uncatchable_trace_unrelated.rs
crates/air-lib/trace-handler/src/lib.rs
crates/air-lib/trace-handler/src/merger/mod.rs

This commit adds a set of trace-related negative tests for UncatchableError [fixes VM-263]

chore(execution-engine): this commit adds a set of trace-related negative tests for UncatchableError [fixes VM-263]

---

crates/beautifier/src/beautifier.rs
crates/beautifier/src/tests/beautifier.rs

It was not printed before by mistake.

fix(air-beautifier): print fold's last_instruction

---

README.md
docs/AIR.md
docs/update-guide.md

chore: fix typos

---

air/src/runner.rs
crates/air-lib/utils/src/lib.rs

A little refactoring to actually publish AquaVM 0.51.

feat(execution-engine)!: intro farewell_if_error_macro

---

air/Cargo.toml
air/benches/nox_tc2_benchmark.rs

This test is for network team to detect nox performance metrics variation.

chore(tests): etalon benchmarking test for network team convenience

---

Cargo.lock
air-interpreter/src/marine.rs
air/src/human_readable_data.rs
air/src/lib.rs
air/src/preparation_step/mod.rs
avm/server/src/errors.rs
avm/server/src/runner.rs
crates/air-lib/interpreter-interface/src/interpreter_outcome.rs
tools/cli/air/Cargo.toml
tools/cli/air/src/data.rs
tools/cli/air/src/main.rs
tools/cli/air/src/trace/run.rs
tools/cli/air/src/trace/run/native.rs
tools/cli/air/src/trace/run/runner.rs
tools/cli/air/src/trace/run/wasm.rs

Add new interpreter method `to_human_readable_data` and `air data` subcommand to convert binary data to JSON with indentation.

feat(air,air-cli): pretty-printing binary interpreter data

---

benches/PERFORMANCE.json
benches/PERFORMANCE.txt

This patch bumps minor version for the delivered artifacts.

feat(performance)!: update perf database and trigger a minor version bump

---

tools/wasm/air-near-contract/Cargo.lock
tools/wasm/air-near-contract/Cargo.toml
tools/wasm/air-near-contract/rust-toolchain.toml
tools/wasm/air-near-contract/src/lib.rs

It fixes several vulnerabilities in deps

fix(dep): update air-near-contract deps
